[package]
name = "driver"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
win-sys = { path = "../win-sys" }

[build-dependencies]
builder = { path = "../builder" }
